### ISSUE TITLE
restarting with pm2 deploy in post-deploy causes error

### ISSUE THREAD

**Issue by aequasi** [Unitech/pm2-deploy#125]
Getting a weird error, only when i restart the script using post-deploy

`pm2 startOrRestart ecosystem.json --env production`

```
0|LFGBot   | SyntaxError: Unexpected token =
0|LFGBot   |     at exports.runInThisContext (vm.js:53:16)
0|LFGBot   |     at Module._compile (module.js:387:25)
0|LFGBot   |     at Object.Module._extensions..js (module.js:422:10)
0|LFGBot   |     at Module.load (module.js:357:32)
0|LFGBot   |     at Function.Module._load (module.js:314:12)
0|LFGBot   |     at Function._load (/usr/local/share/.config/yarn/global/node_modules/pmx/lib/transaction.js:92:21)
0|LFGBot   |     at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/pm2/lib/ProcessContainerFork.js:53:21)
0|LFGBot   |     at Module._compile (module.js:413:34)
0|LFGBot   |     at Object.Module._extensions..js (module.js:422:10)
0|LFGBot   |     at Module.load (module.js:357:32)
```

**Comment by vmarchaud** [comment]
Platform ? PM2/Node version ?
This seems to be related to your application

**Comment by aequasi** [comment]
![image](https://cloud.githubusercontent.com/assets/896295/23108051/0ec63294-f6bc-11e6-9b10-912d96417171.png)

Running `pm2 startOrRestart ecosystem.json --env production` on the server itself, as the user, works fine.
