### ISSUE TITLE
Deploy failed when deploy

### ISSUE THREAD

**Issue by apoutchika** [Unitech/pm2-deploy#150]
Hello,

When i  deploy my project, pm2 deploy output is "Deploy failed", with not other errors or logs.

This work fine when i start my project, but now (after node update ?) pm2 deploy output is always :

```bash
$ pm2 deploy release
Deploy failed
```
My ecosystem.config.js : 
``` javascript
module.exports = {
  apps: [
    {
      name: 'app',
      script: 'server.js',
      env: {
        COMMON_VARIABLE: 'true',
        PORT: 3001
      },
      env_production: {
        NODE_ENV: 'production'
      },
      exec_mode: 'cluster',
      instances: 'max'
    }
  ],
  deploy: {
    release: {
      user: 'node8',
      host: {
        port: '7891',
        host: 'mydomain.com'
      },
      ref: 'origin/release',
      repo: 'git@myrepo.com:myapp.git',
      path: '/home/node8/myapp/',
      'post-deploy': 'npm i && npm run build && pm2 startOrGracefulReload ecosystem.config.js --env production'
    }
  }
}
```

My versions : 
- debian 9
- node: v9.0.0
- npm: 5.5.1
- pm2: 2.7.2

Thank you in advance,
Apoutchika

**Comment by phra** [comment]
i see that there are some `node8` references in the config.. are they still valid after your upgrade?

do you confirm that is working with node 8.x.x but failing with node 9.x.x ?
did you also tried to remove and setup again the deployment?

**Comment by vmarchaud** [comment]
Sadly there are no verbose log [here](https://github.com/Unitech/pm2/blob/master/lib/API/Deploy.js#L109), can you try to `git clone` the pm2 repo, add a `console.log(err)` here and use the binary in `./bin/pm2` where you cloned the repo ?

**Comment by apoutchika** [comment]
I try with node 8, i have same issue.

The console log return this : 
```javascript
Deploy failed
{ Error
    at new ValidationError (/tmp/pm2/node_modules/tv4/tv4.js:1461:12)
    at ValidatorContext.createError (/tmp/pm2/node_modules/tv4/tv4.js:359:14)
    at ValidatorContext.validateType (/tmp/pm2/node_modules/tv4/tv4.js:751:14)
    at ValidatorContext.validateBasic (/tmp/pm2/node_modules/tv4/tv4.js:721:19)
    at ValidatorContext.validateAll (/tmp/pm2/node_modules/tv4/tv4.js:599:19)
    at ValidatorContext.validateObjectProperties (/tmp/pm2/node_modules/tv4/tv4.js:1010:21)
    at ValidatorContext.validateObject (/tmp/pm2/node_modules/tv4/tv4.js:961:11)
    at ValidatorContext.validateAll (/tmp/pm2/node_modules/tv4/tv4.js:603:11)
    at Object.validate (/tmp/pm2/node_modules/tv4/tv4.js:1573:24)
    at Object.deployForEnv (/tmp/pm2/node_modules/pm2-deploy/deploy.js:52:12)
  message: 'Invalid type: object (expected string/array)',
  params: { type: 'object', expected: 'string/array' },
  code: 0,
  dataPath: '/host',
  schemaPath: '/properties/host/type',
  subErrors: null,
  stack: 'Error\n    at new ValidationError (/tmp/pm2/node_modules/tv4/tv4.js:1461:12)\n    at ValidatorContext.createError (/tmp/pm2/node_modules/tv4/tv4.js:359:14)\n    at ValidatorContext.validateType (/tmp/pm2/node_modules/tv4/tv4.js:751:14)\n    at ValidatorContext.validateBasic (/tmp/pm2/node_modules/tv4/tv4.js:721:19)\n    at ValidatorContext.validateAll (/tmp/pm2/node_modules/tv4/tv4.js:599:19)\n    at ValidatorContext.validateObjectProperties (/tmp/pm2/node_modules/tv4/tv4.js:1010:21)\n    at ValidatorContext.validateObject (/tmp/pm2/node_modules/tv4/tv4.js:961:11)\n    at ValidatorContext.validateAll (/tmp/pm2/node_modules/tv4/tv4.js:603:11)\n    at Object.validate (/tmp/pm2/node_modules/tv4/tv4.js:1573:24)\n    at Object.deployForEnv (/tmp/pm2/node_modules/pm2-deploy/deploy.js:52:12)' }
```
It's because the host deploy parameter is bad formated ?

**Comment by vmarchaud** [comment]
As you can see, the problem is the `host` property, you need to configure it like this : `"host": "mydomain:7891"`

**Comment by apoutchika** [comment]
Thank you for you'r fast response !

with the `"host": "mydomain:7891"` the deploy failed with this error : 

````
ssh: Could not resolve hostname mydomain:5172: Name or service not known
````

But i have found the good config : 

```
    release: {
      user: 'node8',
      host: 'mydomain.com',
      port: '7891',
      ref: 'origin/release',
      repo: 'git@myrepo.com:myapp.git',
      path: '/home/node8/myapp/',
      'post-deploy': 'npm i && npm run build && pm2 startOrGracefulReload ecosystem.config.js --env production'
    }
```

It work ! Thank you :-)

**Comment by phra** [comment]
happy to see this resolved! :smile:

**Comment by Steveb-p** [comment]
For those who might stumble upon this looking for a way to change ssh port in new pm2:
```javascript
deploy : {
    production : {
      user : 'node8',
      host : 'mydomain.com',
      ssh_options: [
        'Port=59990',
      ],
      ref  : 'origin/release',
      repo : 'git@myrepo.com:myapp.git',
      path : '/home/node8/myapp',
      'post-deploy' : 'npm i && npm run build && pm2 startOrGreacefulReload ecosystem.config.js --env production'
    }
  }
```
Might work for you, as it did for me (since port is no longer one of possible parameters).
