### ISSUE TITLE
Erro on create ecosystem file on windows

### ISSUE THREAD

**Issue by marcioamr** [Unitech/pm2-deploy#73]
I get the following error on execute pm2 ecosystem command on Windows.

```javascript
pm2 ecosystem
```
Get error:

```javascript
TypeError: Arguments to path.join must be strings
    at f (path.js:204:15)
    at Object.filter (native)
    at Object.exports.join (path.js:209:40)
    at Object.CLI.generateSample (C:\Users\marcior\AppData\Roaming\npm\node_modules\pm2\lib\CLI.js:1355:27)
    at Command.commander.command.option.option.option.option.option.description.action.line (C:\Users\marcior\AppData\Roaming\npm\node_modules\pm2\bin
\pm2:584:9)
    at Command.listener (C:\Users\marcior\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:301:8)
    at Command.emit (events.js:98:17)
    at Command.parseArgs (C:\Users\marcior\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:615:12)
    at Command.parse (C:\Users\marcior\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:458:21)
    at beginCommandProcessing (C:\Users\marcior\AppData\Roaming\npm\node_modules\pm2\bin\pm2:121:13)

path.js:204
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at f (path.js:204:15)
    at Object.filter (native)
    at Object.exports.join (path.js:209:40)
    at Object.CLI.generateSample (C:\Users\marcior\AppData\Roaming\npm\node_modules\pm2\lib\CLI.js:1359:45)
    at Command.commander.command.option.option.option.option.option.description.action.line (C:\Users\marcior\AppData\Roaming\npm\node_modules\pm2\bin
\pm2:584:9)
    at Command.listener (C:\Users\marcior\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:301:8)
    at Command.emit (events.js:98:17)
    at Command.parseArgs (C:\Users\marcior\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:615:12)
    at Command.parse (C:\Users\marcior\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:458:21)
    at beginCommandProcessing (C:\Users\marcior\AppData\Roaming\npm\node_modules\pm2\bin\pm2:121:13)
```

Any idea how to fix?

**Comment by anddo** [comment]
I got the error too.

**Comment by Spown** [comment]
eyep, same here. is anybody even watching bugreports?
